spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: nexwork3@gmail.com
    password: gplm ywld boff nqgm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

accounts:
  host: ${ACCOUNTS_API_URI:}

server:
  port: 8086
