spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://localhost:27017/notifications-db}
  mail:
    host: smtp.gmail.com
    port: 587
    username: nexwork3@gmail.com
    password: gplm ywld boff nqgm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
server:
  port: 8085